---
title: "data analysis notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Analysis

This is to record what I did/what I plan to do so that I don't get confused and forget, and also for general organization and making this study replicatable.

------------------------------------------------------------------------

## Main question

Do changes in maternal care induce adaptive plasticity effects on offspring personality in wild North American red squirrels?

### Hypotheses & predictions

-   Changes in maternal care induces adaptive plasticity effects on offspring personality traits to prepare them for competitive environments

    -   Density cues will alter maternal care; direction unsure

    -   Red squirrel mothers experiencing high density cues will produce less active and more aggressive offspring, shaping them through maternal care style

-   These changes are adaptive

    -   We will observe better survival in individuals with low activity and high aggression in high density years

-   Sex-biased territory bequeathal (towards female offspring) causes LSR effects on aggression

    -   More females means more competition for the territory, which could in a more antagonistic nest environment and increase aggression

------------------------------------------------------------------------

## DATA WRANGLING 4/14/22 12:14 NEED TO UPDATE SAMPLE SIZES AFTER INCLUDING RR AND SUX

### Personality

All juvenile personality data from the master file (n = 559 trials)

Filters:

-   Only those in JO, RR, BT, KL, SU, SUX: n = 544

-   Those that did not indicate that they needed to be excluded/used with caution (n = 430)

-   Excluded Trial 1 for KL 2017-2018 squirrels as they were too young at the time, Trial 2 for squirrels that had 2 trials, removed squirrel_id = 19257 trial 1 because it was too young at time of trial (n = 348)

-   Made sure each squirrel was counted only once (n = 281)

-   Removed the ones that had no OFT/MIS (n = 261)

Ran PCA using *ade4* package on the 261 remaining individuals

OFT loadings were flipped so multiplied by -1

### Nest Attendance

### Used all available data (n = 824)

Based on what SWK did, copy and make new file to add column for censored latencies

NA values/mom did not return were set to 420

m_return and m_move were recoded to binary variables indicating whether mom returned/moved (1) or not (0)

Filters:

-   only used Nest 1 (n = 451)

-   removed ambiguous cases where m_return/move were coded as "y" but there was no time stated for whatever reason (n = 428)

------------------------------------------------------------------------

## Datasets:

master: includes everything (n = 255)

recent4: only 2018-2021 (n = 123)

no. of unique juvs with nest attendance data: 102

-   returned (y/n): 52/50

-   moved (y/n): 37/65

no nest attendance data: 153

all juvs in the tables have both oft and mis data

------------------------------------------------------------------------

## Analyses

### \#1: Survival \~ Personality

-   DATASET: master

-   MODEL: glmer

-   FORMULA: survived_200d \~ (oft1 \* grid density) + (mis1 \* grid density) + mastyear + (1 \| litter_id)

### \#2: Personality \~ Treatments

-   DATASET: recent4

-   MODEL: lmer

-   FORMULA: personality \~ (treatment \* sex) + growthrate + year (factor) + (1 \| litter_id)

    -   separate model for oft1 and mis1

### \#3: Personality \~ Maternal Care

-   DATASET: master

-   MODEL: lmer

-   FORMULA: personality \~ return,move (binary response) + sex + (1 \| year) + (1 \| litter_id)

### \#4: Maternal Care \~ Treatment

-   DATASET: master

-   MODEL: lmer (or glmer if i use the binary for return/move)

-   FORMULA: care \~ treatment + n_pups

    -   separate model for each
