---
title: "README"
author: "Deborah Ho"
date: "4/23/2022"
output: 
  html_document: 
    toc: yes
    theme: spacelab
    number_sections: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Does maternal care induce adaptive changes in offspring behavioral characteristics in wild North American red squirrels (*Tamiasciurus hudsonicus*)?

This repository contains the data and code used in all analyses for my Master's thesis written in 2022 as part of the AMDP requirements.

### data

All the raw data I used for my study are in this folder.

#### personality-master

This file contains *processed* personality data from behavioral assay until 2021.

#### AllNests

This file contains all nest attendance data transcribed from the nest sheets in the field until 2021.

#### AllNestsCENS

This file is similar to AllNests, except with additional columns (*return_lat* and *move_lat*) for censoring all latencies to 420 seconds. This means that if a mother did not return to her pups or move her pups within 7 minutes (i.e. 420 seconds), the latency was recorded as 420 seconds in these columns.

### scripts

This folder contains all the scripts I used to load in data, clean data, run my analyses, and generate my figures.

#### packages.R

This script has all the packages used in the analyses. Running this whole script first will load all the required packages.

#### dataimport.R

This script was used for accessing the KRSP database, as well as pulling tables from it to obtain additional data needed to run my analyses. You will need a KRSP database login ID and password to run this script and get access to the database.

#### personality.R

I used this script to load in raw personality data from *personality-master.csv*, clean the data, and run PCA on personality data to obtain my PC scores for OFT and MIS.

In my case, I was only using weaned juveniles (60-80 days old at the time of the behavioral assays).

#### nestattendance.R

#### survival.R

#### density.R

#### dataconsol.R

#### analysis.R

#### plots.R

### output

All plots generated in `plots.R` are saved in this folder.

### analysis-notes.Rmd

Rmd doc I used to track sample sizes so that I could see how many trials I lost with each additional filter added.

I also used this to plan my analyses, including what my models should look like and the data sets I would use for them.
